# Generated by Django 3.1 on 2020-10-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('user', 'listing')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listing')},
        ),
    ]
